name = "Stargate: ReLeveled"
author = "RedÎ›ngel"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52616fcd5b104f529ea3adc89f6984928ece14eada7c53b00271943e6c443467"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
