name = "Stargate: ReLeveled"
author = "RedÎ›ngel"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47107fe1bf55bc3184842361966101f1e3a9f676e3104f384d01c8f8781e30a0"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
